// NOTE: Example Data

export const GET_EXAMPLE_DATA = "GET_EXAMPLE_DATA";
export const GET_EXAMPLE_DATA_LOADING = "GET_EXAMPLE_DATA_LOADING";
export const GET_EXAMPLE_DATA_SUCCESS = "GET_EXAMPLE_DATA_SUCCESS";
export const GET_EXAMPLE_DATA_ERROR = "GET_EXAMPLE_DATA_ERROR";

// NOTE: Register Action Constant

export const REGISTER_USER_DATA = "REGISTER_USER_DATA";
export const REGISTER_USER_DATA_LOADING = "REGISTER_USER_DATA_LOADING";
export const REGISTER_USER_DATA_SUCCESS = "REGISTER_USER_DATA_SUCCESS";
export const REGISTER_USER_DATA_ERROR = "REGISTER_USER_DATA_ERROR";
